AWSTemplateFormatVersion: 2010-09-09
Description: This project checks the certificates referenced in prism are up to date, otherwise warns the respective team owners.
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: deploy
  App:
    Description: Application name
    Type: String
    Default: certificate-watchdog
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: deploy-tools-dist
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
  Subnets:
    Description: VPC's subnets
    Type: List<AWS::EC2::Subnet::Id>
  PrismDomain:
    Description: Prism domain
    Type: String
  SenderEmail:
    Description: Email to use as a source when sending notifications
    Type: String
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: email
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - ses:SendEmail
              Resource: "*"
        - PolicyName: vpc
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: "*"

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open access to prism
      VpcId: !Ref VpcId

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
          PrismDomain: !Ref PrismDomain
          SenderEmail: !Ref SenderEmail
      Description: Checks the validity of ACM certificates
      Handler: com.gu.certw.Lambda::handler
      MemorySize: 256
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 120
      VpcConfig:
        SubnetIds: !Ref Subnets
        SecurityGroupIds: [!GetAtt LambdaSecurityGroup.GroupId]

  DailyEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Event sent to trigger the certificate-watchdog lambda
      ScheduleExpression: cron(0 10 * * ? *)
      Targets:
        - Id: Lambda
          Arn: !GetAtt Lambda.Arn

  DailyEventLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Lambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyEvent.Arn